// Generated by bilt-cloud from this project's database schema. Do not edit.
// Regenerated on every schema change; edits are overwritten.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

declare module '@biltme/backend' {
  interface Database {
    public: {
      Tables: {
        checkins: {
          Row: {
            id: string;
            user_id: string;
            checkin_date: string;
            mood: number;
            energy: number;
            stress: number;
            focus: number;
            sleep_hours: number | null;
            activity_minutes: number | null;
            meeting_count: number | null;
            work_hours: number | null;
            note: string | null;
            created_at: string;
          };
          Insert: {
            id?: string;
            user_id: string;
            checkin_date: string;
            mood: number;
            energy: number;
            stress: number;
            focus: number;
            sleep_hours?: number | null;
            activity_minutes?: number | null;
            meeting_count?: number | null;
            work_hours?: number | null;
            note?: string | null;
            created_at?: string;
          };
          Update: {
            id?: string;
            user_id?: string;
            checkin_date?: string;
            mood?: number;
            energy?: number;
            stress?: number;
            focus?: number;
            sleep_hours?: number | null;
            activity_minutes?: number | null;
            meeting_count?: number | null;
            work_hours?: number | null;
            note?: string | null;
            created_at?: string;
          };
          Relationships: [];
        };
        goal_action_logs: {
          Row: {
            id: string;
            user_id: string;
            goal_action_id: string;
            log_date: string;
            status: 'completed' | 'skipped';
            created_at: string;
          };
          Insert: {
            id?: string;
            user_id: string;
            goal_action_id: string;
            log_date?: string;
            status?: 'completed' | 'skipped';
            created_at?: string;
          };
          Update: {
            id?: string;
            user_id?: string;
            goal_action_id?: string;
            log_date?: string;
            status?: 'completed' | 'skipped';
            created_at?: string;
          };
          Relationships: [
            {
              foreignKeyName: 'goal_action_logs_action_owner_fkey';
              columns: ['goal_action_id', 'user_id'];
              isOneToOne: false;
              referencedRelation: 'goal_actions';
              referencedColumns: ['id', 'user_id'];
            },
          ];
        };
        goal_actions: {
          Row: {
            id: string;
            user_id: string;
            goal_id: string;
            title: string;
            schedule_days: number[];
            sort: number;
            is_active: boolean;
            created_at: string;
            updated_at: string;
          };
          Insert: {
            id?: string;
            user_id: string;
            goal_id: string;
            title: string;
            schedule_days?: number[];
            sort?: number;
            is_active?: boolean;
            created_at?: string;
            updated_at?: string;
          };
          Update: {
            id?: string;
            user_id?: string;
            goal_id?: string;
            title?: string;
            schedule_days?: number[];
            sort?: number;
            is_active?: boolean;
            created_at?: string;
            updated_at?: string;
          };
          Relationships: [
            {
              foreignKeyName: 'goal_actions_goal_owner_fkey';
              columns: ['goal_id', 'user_id'];
              isOneToOne: false;
              referencedRelation: 'goals';
              referencedColumns: ['id', 'user_id'];
            },
          ];
        };
        goal_logs: {
          Row: {
            id: string;
            user_id: string;
            goal_id: string;
            log_date: string;
            created_at: string;
          };
          Insert: {
            id?: string;
            user_id: string;
            goal_id: string;
            log_date: string;
            created_at?: string;
          };
          Update: {
            id?: string;
            user_id?: string;
            goal_id?: string;
            log_date?: string;
            created_at?: string;
          };
          Relationships: [
            {
              foreignKeyName: 'goal_logs_goal_id_fkey';
              columns: ['goal_id'];
              isOneToOne: false;
              referencedRelation: 'goals';
              referencedColumns: ['id'];
            },
          ];
        };
        goals: {
          Row: {
            id: string;
            user_id: string;
            title: string;
            category: string | null;
            is_custom: boolean;
            sort: number;
            created_at: string;
            archived_at: string | null;
            kind: 'habit' | 'outcome';
            description: string | null;
            target_date: string | null;
            habit_days: number[];
            status: 'active' | 'paused' | 'completed' | 'archived';
            updated_at: string;
          };
          Insert: {
            id?: string;
            user_id: string;
            title: string;
            category?: string | null;
            is_custom?: boolean;
            sort?: number;
            created_at?: string;
            archived_at?: string | null;
            kind?: 'habit' | 'outcome';
            description?: string | null;
            target_date?: string | null;
            habit_days?: number[];
            status?: 'active' | 'paused' | 'completed' | 'archived';
            updated_at?: string;
          };
          Update: {
            id?: string;
            user_id?: string;
            title?: string;
            category?: string | null;
            is_custom?: boolean;
            sort?: number;
            created_at?: string;
            archived_at?: string | null;
            kind?: 'habit' | 'outcome';
            description?: string | null;
            target_date?: string | null;
            habit_days?: number[];
            status?: 'active' | 'paused' | 'completed' | 'archived';
            updated_at?: string;
          };
          Relationships: [];
        };
        insights: {
          Row: {
            id: string;
            user_id: string;
            kind: string;
            title: string;
            body: string;
            action: string | null;
            insight_date: string;
            created_at: string;
          };
          Insert: {
            id?: string;
            user_id: string;
            kind?: string;
            title: string;
            body: string;
            action?: string | null;
            insight_date?: string;
            created_at?: string;
          };
          Update: {
            id?: string;
            user_id?: string;
            kind?: string;
            title?: string;
            body?: string;
            action?: string | null;
            insight_date?: string;
            created_at?: string;
          };
          Relationships: [];
        };
        profiles: {
          Row: {
            id: string;
            first_name: string | null;
            age_range: string | null;
            country: string | null;
            timezone: string | null;
            life_stage: string | null;
            responsibilities: string[];
            challenges: string[];
            disclaimer_accepted_at: string | null;
            onboarding_completed_at: string | null;
            created_at: string;
            updated_at: string;
          };
          Insert: {
            id: string;
            first_name?: string | null;
            age_range?: string | null;
            country?: string | null;
            timezone?: string | null;
            life_stage?: string | null;
            responsibilities?: string[];
            challenges?: string[];
            disclaimer_accepted_at?: string | null;
            onboarding_completed_at?: string | null;
            created_at?: string;
            updated_at?: string;
          };
          Update: {
            id?: string;
            first_name?: string | null;
            age_range?: string | null;
            country?: string | null;
            timezone?: string | null;
            life_stage?: string | null;
            responsibilities?: string[];
            challenges?: string[];
            disclaimer_accepted_at?: string | null;
            onboarding_completed_at?: string | null;
            created_at?: string;
            updated_at?: string;
          };
          Relationships: [];
        };
        reset_actions: {
          Row: {
            id: string;
            user_id: string;
            session_id: string;
            title: string;
            horizon: 'next_five_minutes' | 'today' | 'this_week';
            sort: number;
            completed_at: string | null;
            created_at: string;
          };
          Insert: {
            id?: string;
            user_id: string;
            session_id: string;
            title: string;
            horizon: 'next_five_minutes' | 'today' | 'this_week';
            sort?: number;
            completed_at?: string | null;
            created_at?: string;
          };
          Update: {
            id?: string;
            user_id?: string;
            session_id?: string;
            title?: string;
            horizon?: 'next_five_minutes' | 'today' | 'this_week';
            sort?: number;
            completed_at?: string | null;
            created_at?: string;
          };
          Relationships: [
            {
              foreignKeyName: 'reset_actions_session_owner_fkey';
              columns: ['session_id', 'user_id'];
              isOneToOne: false;
              referencedRelation: 'reset_sessions';
              referencedColumns: ['id', 'user_id'];
            },
          ];
        };
        reset_items: {
          Row: {
            id: string;
            user_id: string;
            session_id: string;
            content: string;
            category: string;
            decision: string | null;
            horizon: string | null;
            sort: number;
            completed_at: string | null;
            created_at: string;
          };
          Insert: {
            id?: string;
            user_id: string;
            session_id: string;
            content: string;
            category?: string;
            decision?: string | null;
            horizon?: string | null;
            sort?: number;
            completed_at?: string | null;
            created_at?: string;
          };
          Update: {
            id?: string;
            user_id?: string;
            session_id?: string;
            content?: string;
            category?: string;
            decision?: string | null;
            horizon?: string | null;
            sort?: number;
            completed_at?: string | null;
            created_at?: string;
          };
          Relationships: [
            {
              foreignKeyName: 'reset_items_session_id_fkey';
              columns: ['session_id'];
              isOneToOne: false;
              referencedRelation: 'reset_sessions';
              referencedColumns: ['id'];
            },
          ];
        };
        reset_sessions: {
          Row: {
            id: string;
            user_id: string;
            brain_dump: string;
            stage: string;
            coach_summary: string | null;
            why_prompt: string | null;
            why_reflection: string | null;
            crisis_flagged: boolean;
            completed_at: string | null;
            created_at: string;
            updated_at: string;
            plan_generated_at: string | null;
            coach_degraded: boolean;
            closing_line: string | null;
          };
          Insert: {
            id?: string;
            user_id: string;
            brain_dump?: string;
            stage?: string;
            coach_summary?: string | null;
            why_prompt?: string | null;
            why_reflection?: string | null;
            crisis_flagged?: boolean;
            completed_at?: string | null;
            created_at?: string;
            updated_at?: string;
            plan_generated_at?: string | null;
            coach_degraded?: boolean;
            closing_line?: string | null;
          };
          Update: {
            id?: string;
            user_id?: string;
            brain_dump?: string;
            stage?: string;
            coach_summary?: string | null;
            why_prompt?: string | null;
            why_reflection?: string | null;
            crisis_flagged?: boolean;
            completed_at?: string | null;
            created_at?: string;
            updated_at?: string;
            plan_generated_at?: string | null;
            coach_degraded?: boolean;
            closing_line?: string | null;
          };
          Relationships: [];
        };
        wellbeing_baseline: {
          Row: {
            user_id: string;
            energy: number;
            stress: number;
            motivation: number;
            sleep_quality: number;
            physical_activity: number;
            life_satisfaction: number;
            work_satisfaction: number;
            created_at: string;
          };
          Insert: {
            user_id: string;
            energy: number;
            stress: number;
            motivation: number;
            sleep_quality: number;
            physical_activity: number;
            life_satisfaction: number;
            work_satisfaction: number;
            created_at?: string;
          };
          Update: {
            user_id?: string;
            energy?: number;
            stress?: number;
            motivation?: number;
            sleep_quality?: number;
            physical_activity?: number;
            life_satisfaction?: number;
            work_satisfaction?: number;
            created_at?: string;
          };
          Relationships: [];
        };
      };
      Views: { [_ in never]: never };
      Functions: { [_ in never]: never };
      Enums: { [_ in never]: never };
      CompositeTypes: { [_ in never]: never };
    };
  }
}
